# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57f26452b626c5beb3ed9a15f0c50d4ebb4bb6837b425efb4517e5c346a3c2fec7d8b4060ec9378a7828abb85972bc68fd4af234e6a0174b942215bca9fd8ae8

test:
  secret_key_base: b9f589f534c1aecc60ba3022212e4e94f851a10c40f3d1b92bf5cb0a1a3f1d29eb687468f72db96bd5f1d8cb7c4b3bb355edb5e7efbc38fa946b73ba9a33d616

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
